Add IoT Security to App/Addon
PaloAltoNetworks/Splunk-Apps pull request #158
Opened 2020-12-31 07:55 UTC by paulmnguyen

## Description

IoT Security integration with Palo Alto Networks Splunk Application.

## Motivation and Context

Provide visibility into IoT Security

## How Has This Been Tested?

Tested on Standalone server.

## Screenshots (if appropriate)

## Types of changes

- New feature (non-breaking change which adds functionality)

## Checklist

- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes if appropriate.
- [ ] All new and existing tests passed.

2020-12-31 21:08 UTC, btorresgil requested changes
There's a lot of formatting changes in the files that aren't related to IoT. Also a lot of changes to wildfire and autofocus that aren't related. Can these be put in a different PR? Where they made by Add-on Builder?

2020-12-31 21:08 UTC, btorresgil commented on Splunk_TA_paloalto/bin/input_module_iot_security.py
> +    if not last_device_pull or datetime.datetime.strptime(last_device_pull, "%Y-%m-%d %H:%M:%S") < datetime.datetime.now() - datetime.timedelta(minutes=5):
Need a comment here about why we chose this criteria for performing a device fetch.

2020-12-31 21:15 UTC, paulmnguyen commented on Splunk_TA_paloalto/README.txt
> +This is an add-on powered by the Splunk Add-on Builder.
Yes

2020-12-31 21:16 UTC, paulmnguyen commented on Splunk_TA_paloalto/README/inputs.conf.spec
> -# url =
Yea also add on builder

2020-12-31 21:17 UTC, paulmnguyen commented on Splunk_TA_paloalto/app.manifest
> +      "version": "6.6.0b"
Sorry i changed it in order to create an export in add on builder

2020-12-31 21:17 UTC, paulmnguyen commented on Splunk_TA_paloalto/default/app.conf
> +state_change_requires_restart = true
Yup add on builder added it.

2020-12-31 21:20 UTC, btorresgil commented on Splunk_TA_paloalto/bin/input_module_iot_security.py
> +def query_api(helper, url, parameters, api_type, proxy_enabled):
You probably don't have time to do this before you leave, so we'll leave it as-is. But I'd like to write unit tests and refactor this at some point.

2021-01-09 18:07 UTC, btorresgil commented on Splunk_TA_paloalto/app.manifest
> +      "developmentStatus": "Beta"
Added this to develop

2021-01-12 20:22 UTC, btorresgil approved these changes

2021-01-12 20:31 UTC, merged