Update to addon builder 4.1.1
PaloAltoNetworks/Splunk-Apps pull request #270
Opened 2022-10-25 16:52 UTC by paulmnguyen

## Description

Add-on builder has been updated to 4.1.1 in order to pass certification we have to update to the latest version

## Motivation and Context

Splunk certification is failing because of the jquery dependencies.

## How Has This Been Tested?

## Screenshots (if appropriate)

## Types of changes

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes if appropriate.
- [ ] All new and existing tests passed.

2022-10-25 21:28 UTC, paulmnguyen commented
Still failing python checks I will need to resolve these checks before we can merge.

2022-11-30 18:40 UTC, btorresgil requested changes

2022-11-30 18:40 UTC, btorresgil commented on Splunk_TA_paloalto/appserver/static/js/build/globalConfig.json
> +        "version": "7.1.0",
"version" should be `0.0.0-develop`

2022-11-30 19:17 UTC, btorresgil approved these changes

2022-11-30 19:20 UTC, merged